#!/bin/bash
# Install Skype on a Fedora box.

# Get Fedora version
FEDORA_VERSION=`rpm -q --queryformat '%{VERSION}\n' fedora-release`

if [ "$FEDORA_VERSION" -ge "23" ]
then
  PKGER=`whereis dnf | cut -d ' ' -f 2`
else
  PKGER=`whereis yum | cut -d ' ' -f 2`
fi

echo "Installing dependences..."
$PKGER -yq install alsa-lib.i686 fontconfig.i686 freetype.i686 glib2.i686 libSM.i686 libXScrnSaver.i686 libXi.i686 libXrandr.i686 libXrender.i686 libXv.i686 libstdc++.i686 pulseaudio-libs.i686 qt.i686 qt-x11.i686 zlib.i686 qtwebkit.i686 wget

echo "Getting and unpacking on /opt..."
cd /tmp
wget --trust-server-names http://www.skype.com/go/getskype-linux-dynamic
VERSION=`ls skype* | cut -d '-' -f 2 | sed -e s/[^0-9]//g`
mkdir /opt/skype-$VERSION
ln -s /opt/skype-$VERSION /opt/skype
tar xvf skype*bz2 -C /opt/skype --strip-components=1

echo "Making links..."
ln -s /opt/skype/skype.desktop /usr/share/applications/skype.desktop
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/icons/skype.png
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/pixmaps/skype.png

echo "Generating executable..."
touch /usr/bin/skype
chmod 755 /usr/bin/skype

# Put this into /usr/bin/skype
cat << EOF > /usr/bin/skype
#!/bin/sh
export SKYPE_HOME="/opt/skype"
\$SKYPE_HOME/skype --resources=\$SKYPE_HOME \$*
EOF

